# Generated by Django 5.0.4 on 2024-04-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abteilungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerischername', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Abteilungsleiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seit', models.DateField()),
                ('bis', models.DateField(blank=True, null=True)),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.abteilungen')),
                ('leiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Abteilungsleiter')),
            ],
        ),
        migrations.CreateModel(
            name='Personalzuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seit', models.DateField()),
                ('bis', models.DateField(blank=True, null=True)),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.abteilungen')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abteilungen',
            name='personal',
            field=models.ManyToManyField(through='beurteilung.Personalzuordnung', to=settings.AUTH_USER_MODEL),
        ),
    ]
