# Generated by Django 5.0.4 on 2025-06-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abteilungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerischername', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Addresatentemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adressatentemplatebezeichnung', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungsauspraegungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteilungsausprägung', models.CharField(max_length=50)),
                ('punktwertmax', models.IntegerField()),
                ('punktwertmin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungsgliederung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gliederung', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungstemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteilungstemplate_bezeichnung', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Abteilungsleiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seit', models.DateField()),
                ('bis', models.DateField(blank=True, null=True)),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.abteilungen')),
                ('leiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Abteilungsleiter')),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteilung_bez', models.CharField(max_length=255)),
                ('beurteilung_erl', models.CharField(max_length=255)),
                ('beurteilung_frist', models.DateField()),
                ('beurteilung_erläuterung', models.TextField()),
                ('beurteilter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beurteilungstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilung_beurteiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beurteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungen')),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungsmerkmale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteilungsmerkmal', models.CharField(max_length=50)),
                ('beurteilungsauspraegungen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungsauspraegungen')),
                ('untergruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungsgliederung')),
                ('beurteilungstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilung_Beurteilungsmerkmale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_kommentar', models.TextField()),
                ('beurteilung_timestamp', models.DateTimeField(auto_now_add=True)),
                ('beurteiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beurteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungen')),
                ('be_auspraegung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungsauspraegungen')),
                ('be_merkmal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungsmerkmale')),
            ],
        ),
        migrations.AddField(
            model_name='beurteilungsgliederung',
            name='beurteilungstemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungstemplate'),
        ),
        migrations.CreateModel(
            name='Beurteilungsadressaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresatentemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.addresatentemplate')),
                ('beurteilungstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Beurteilungstemplate_Beurteiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beurteiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('beurteilungstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.beurteilungstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Personalzuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seit', models.DateField()),
                ('bis', models.DateField(blank=True, null=True)),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.abteilungen')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abteilungen',
            name='personal',
            field=models.ManyToManyField(through='beurteilung.Personalzuordnung', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='User_Addresatentemplate_zuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Addresatentemplate_zuordnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beurteilung.addresatentemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
