# Generated by Django 5.0.4 on 2025-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beurteilung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beurteilungen',
            name='beurteilung_abgeschlossen',
            field=models.BooleanField(default=False),
        ),
    ]
